# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

surv_weibull <- function(t, lambda, p, rand_unif) {
    .Call('randsurv_surv_weibull', PACKAGE = 'randsurv', t, lambda, p, rand_unif)
}

nrsolve_surv_weibull <- function(lambda, p, rand_unif, init_t = 1, tol = 1e-10, maxiter = 500L) {
    .Call('randsurv_nrsolve_surv_weibull', PACKAGE = 'randsurv', lambda, p, rand_unif, init_t, tol, maxiter)
}

inv_weibull <- function(lambda, p, rand_unif) {
    .Call('randsurv_inv_weibull', PACKAGE = 'randsurv', lambda, p, rand_unif)
}

surv_weibull_compet <- function(t, lambda_1, p_1, lambda_2, p_2, rand_unif) {
    .Call('randsurv_surv_weibull_compet', PACKAGE = 'randsurv', t, lambda_1, p_1, lambda_2, p_2, rand_unif)
}

nrsolve_surv_weibull_compet <- function(lambda_1, p_1, lambda_2, p_2, rand_unif, init_t = 1, tol = 1e-10, maxiter = 500L) {
    .Call('randsurv_nrsolve_surv_weibull_compet', PACKAGE = 'randsurv', lambda_1, p_1, lambda_2, p_2, rand_unif, init_t, tol, maxiter)
}

ddt_surv_weibull_compet <- function(t, lambda_1, p_1, lambda_2, p_2, rand_unif) {
    .Call('randsurv_ddt_surv_weibull_compet', PACKAGE = 'randsurv', t, lambda_1, p_1, lambda_2, p_2, rand_unif)
}

observed_event <- function(t, lambda_1, p_1, lambda_2, p_2) {
    .Call('randsurv_observed_event', PACKAGE = 'randsurv', t, lambda_1, p_1, lambda_2, p_2)
}

